### ISSUE TITLE
Content disappear

### ISSUE THREAD

**Issue by Nickiuan** [bdshields/NFAuthenticationKey#1]
Login with aut key successo, after 3 days all content in netflix repository disappear, reinstalled all but content empty, any solution?

**Comment by bdshields** [comment]
Sorry, I have no idea.

Which Netflix repository are you referring to? The Kodi add-on repo for the Netflix add-on?

**Comment by Nickiuan** [comment]
castagnait repo 
CastagnaIT Repository for KODI 18.x LEIA - repository.castagnait-1.0.1.zip <https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.1.zip>

**Comment by bdshields** [comment]
Bug is unrelated.
